on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make all
      - name: lastest-release
        run: |
          - gh release create ${{ github.ref_name }} --draft -t "${{ github.ref_name }}" -n "Release ${{ github.ref_name }}" --generate-notes --verify-tag
          - gh release upload  ${{ github.ref_name }} AL2023.zip



